device: "auto"
train: # metrics that are calculated during training
  - _target_: src.metrics.MaskedAccuracy
    metric:
      _target_: torchmetrics.classification.MulticlassAccuracy
      num_classes: 8
      average: "micro"
    device: ${metrics.device}
    name: "TrainMaskedMulticlassAccuracy" # just an example to see difference
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.MaskedAccuracy
    metric:
      _target_: torchmetrics.classification.MulticlassAccuracy
      num_classes: 8
      average: "micro"
    device: ${metrics.device}
    name: "TestMulticlassAccuracy"

